formatter: "markdown table" # this is required

#header-from: main.tf
#footer-from: ""

#recursive:
#  enabled: false
#  path: modules
#


sections:
  # all  data-sources  header  footer  inputs  modules  outputs  providers  requirements  resources
  hide: [data-sources, modules, providers, resources, requirements ]
  # show: []

#content: ""

output:
  file: "README.md"
  mode: inject



#output-values:
#  enabled: false
#  from: ""


sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
